module Ota
  TERMS_TYPES = [
    'Acceptable Use Policy',
    'Developer Terms',
    'Trackers Policy',
    'Legal Information',
    'Copyright Claims Policy',
    'Vulnerability Disclosure Policy',
    'Privacy Policy',
    # 'Policy',
    'Community Guidelines',
    'General Conditions of Sale',
    'Terms of Service',
    'Imprint',
    'Trackers Policy',
    'Developer Terms',
    'Deceased Users',
    'Restricted Use Policy',
    'Commercial Terms',
    'Law Enforcement Guidelines',
    'Human Rights Policy',
    'In-App Purchases Policy',
    'Brand Guidelines',
    'Quality Guidelines',
    'Data Controller Agreement',
    'Data Processor Agreement',
    'User Consent Policy',
    'Closed Captioning Policy',
    'Seller Warranty',
    'Single Sign-On Policy',
    'Live Policy',
    'Complaints Policy',
    'Marketplace Buyers Conditions',
    'Marketplace Sellers Conditions',
    'Ranking Parameters Description',
    'Premium Partner Conditions',
    'Platform to Business Notice',
    'Business Mediation Policy',
    'Business Privacy Policy',
    'Frequently Asked Questions',
    'Merged',
    'Charter',
    'Review Guidelines',
    'Human Rights Policy',
    'Data Controller Agreement',
    'Conditions of Carriage',
    'Corporate Social Responsibility',
    'Social Media Policy',
    'Uniform Disclosure',
    'Affiliate Disclosure',
    'Safety Guidelines',
    'Telephone Communication Guidelines',
    'Records Keeping Policy',
    'Service Level Agreement',
    'Spam',
    'Policy',
    'Other',
    'About',
    'Miscellaneous Agreement',
    'General Terms of Business'
  ]

  TERMS_TYPE_KEY_WORDS = {
    'General Terms of Business': [
      'agb'
    ],
    'Service Level Agreement': [
      'sla',
      'service level',
      'service-level'
    ],
    'General Conditions of Sale': [
      'return',
      'returns',
      'refund',
      'refunds',
      'cancellation',
      'shipping',
      'delivery',
      'conditions of sale',
      'warranty',
      'warranties',
      'conditions générales de vente',
      'leveringsvoorwaarden',
      'money back guarantee policy',
      'billing',
      'shopping services & policies',
      'bill',
      'políticas',
      'cgv',
      'سياسة الاسترجاع'
    ],
    'Records Keeping Policy': [
      '2257',
      'record-keeping',
      'data transfer'
    ],
    'Telephone Communication Guidelines': [
      'tcpa',
      'sms'
    ],
    'Uniform Disclosure': [
      'uniform disclosure'
    ],
    'Data Processor Agreement': [
      'processor',
      'subprocesor'
    ],
    'Social Media Policy': [
      'social networking',
      'social media'
    ],
    'Human Rights Policy': [
      'human rights'
    ],
    'Quality Guidelines': [
      'corrections policy',
      'ad quality',
      'material disclosure'
    ],
    'Affiliate Disclosure': [
      'affiliate',
      'linking',
      'links policy',
      'link policy'
    ],
    'Safety Guidelines': [
      'child',
      'children',
      'compromised accounts',
      'two steps verification',
      'online safety',
      'safety guidelines',
      'fraud',
      '2fa',
      'anti-piracy',
      'parental guide'
    ],
    'Corporate Social Responsibility': [
      'educational rights',
      'corruption',
      'fcpa',
      'sustainability',
      'transparency',
      'anti-money laundering',
      'ethics',
      'human trafficking',
      'digital accessibility',
      'non-discrimination',
      'gmos',
      'slavery',
      'socially responsible',
      'diversity',
      'accessibility',
      'mozilla workplace transition policy guidelines',
      'whistleblower',
      'ada'
    ],
    'Data Controller Agreement': [
      'data controller'
    ],
    'Conditions of Carriage': [
      'conditions of carriage',
      'carriage'
    ],
    'Terms of Service': [
      'consumer agreement',
      'acceptance policy',
      'access agreement',
      'terms of service',
      'terms and conditions',
      'terms & conditions',
      'terms & privacy',
      'eula',
      'license',
      'service agreement',
      'end user license agreement',
      'end-user license agreement',
      'end user licence agreement',
      'end-user licence agreement',
      'all policies',
      'terms of use',
      'warunki korzystania',
      'conditions of use',
      'consumer terms of sale',
      'terms of sale',
      'software license agreement',
      'services agreement',
      'privacy policy and terms of use',
      'use agreement',
      'visitor agreement',
      'account agreement',
      'member agreement',
      'terms',
      'tos',
      'term of service',
      'rules and conditions',
      'term of usage',
      'term of use',
      'use policy',
      'usage policy',
      'user agreement',
      'user agreem',
      'enrollment',
      't & c',
      't&c',
      "t's & c's",
      'terns and conditions',
      'term & condition',
      "conditions générales d’utilisation",
      "conditions génerales d'utilisation",
      "conditions générales d'utilisation",
      "conditions générales",
      "termes et conditions",
      "términos y privacidad",
      "orientações de uso",
      'termos de uso',
      'general conditions',
      'use conditions',
      "conditions d'utilisations",
      'términos y condiciones',
      'пользовательское соглашение',
      'conditions generales',
      'allgemeine geschäftsbedingungen',
      'nutzungsbedingungen',
      'пользовательское соглашение об условиях предоставления услуг в интернет-магазине лабиринт',
      'smluvní podmínky služby',
      'felhasználási feltételek',
      "conditions d'utilisation",
      '規約',
      'geschäftsbedingungen',
      'algemene voorwaarden',
      'syarat dan ketentuan',
      'conditions for use',
      'allgemeine geschäfts­bedingungen',
      'usage agreement',
      'соглашение об использовании',
      '飞书用户服务协议',
      'الشروط والأحكام',
      'use policy',
      'allgemeine geschã¤ftsbedingungen',
      'términos de servicio',
      'όροι χρήσης υπηρεσιών',
      'όροι χρήσης',
      'общи условия за потребителите и посетителите на уеб сайта',
      'общи условия за ползване',
      'algemene voorwaarden',
      'term and conditions',
      '利用規約',
      'condiciones',
      'termos de utilização',
      'condiciones generales',
      'όροι και προϋποθέσεις',
      'content deletion policy',
      'basic rules',
      'rgpd',
      'use restrictions policy',
      'usage rules',
      'membership contract',
      'contracte de serveis',
      'customer agreement',
      'subscriber agreement',
      'registration agreement',
      'subscription agreement',
      'user rules',
      'service level agreement',
      'membership agreement',
      'termos de serviço',
      'editorial policy',
      'rules',
      'conditions',
      'participation agreement',
      'consumer agreement',
      'contributor agreement',
      'customer policy',
      '"HERE WeGo, HERE application and HERE Maps Service Terms "',
      'cgu',
      'palveluiden yleiset sopimusehdot'
    ],
    'Privacy Policy': [
      'user rights',
      'client protection',
      'privacy policy',
      'privacy',
      'data policy',
      'data use policy',
      'privacy center',
      'privacy notice',
      'privacy and cookies policy',
      'security & privacy',
      'privacy & security',
      'security and disclosure',
      'data protection',
      'security policy',
      'security details',
      'security overview',
      'security statement',
      'security compliance',
      'security',
      'data security',
      'data agreement',
      'data management',
      'data sharing',
      'proteção de dados',
      'your data',
      'data processing',
      'gdpr',
      'general data protection regulation',
      'data usage',
      'politique de confidentialité',
      'politique de protection des données',
      'política de privacidade cofina',
      'règles de confidentialité',
      'política de uso e privacidade',
      'política de privacidade',
      'polityka prywatności grupa',
      'política de privacidad',
      "notice d'information relative aux données à caractère personnel",
      "privcy policy",
      "aviso de privacidad",
      "mes informations personnelles",
      'política de uso de dados pessoais',
      'aviso de privacidade',
      'politique d’utilisation des données',
      'pravacy policy',
      'políticas de privacidade',
      'политика конфиденциальности',
      'politique de confidentialite',
      'datenschutzerklaerung',
      'соглашение на обработку персональных данных',
      'datenschutzerklärung',
      'положение о постоянно действующей комиссии по защите персональных данных фбун цнии эпидемиологии роспотребнадзора',
      'политика обеспечения конфиденциальности',
      'datenschutzhinweis',
      'datenschutz',
      'datenschutzbestimmungen',
      'политика в отношении обработки персональных данных¹',
      'политика в отношении персональных данных',
      'условия конфиденциальности',
      'personvernerklæring',
      'datenschutzhinweise',
      'persondatapolitik',
      'datenschutzrichtlinien',
      'согласие на обработку персональных данных',
      'условия использования',
      'kebijakan privasi',
      'rozsah zásady osobních ůdajů',
      'personal data rights',
      'charte de confidentialité',
      'privace',
      'как мы обрабатываем ваши персональные данные, которые хранятся на «медузе»',
      'charte de protection des données personnelles',
      'daten­schutz­be­stim­mun­gen',
      'polityka prywatności',
      'pricacy policy',
      'políticas de privacidad',
      'privatpolitik',
      'プライバシーポリシー',
      'private policy',
      '隐私政策',
      'πολιτική ιδιωτικότητας',
      '個人情報保護方針',
      '情報セキュリティ基本方針',
      'politica de confidenţialitate',
      'adatkezelési tájékoztató',
      'соглашение об обработке персональных данных',
      'déclaration de confidentialité',
      'политика за защита на личните данни',
      'protection des données',
      'déclaration de protection des données',
      'privacidad',
      'polityka prywatności',
      'privatumo politika',
      'this service may collect, use, and share location data',
      'who can see your password',
      'does protonvpn store user information',
      'who can see your credit card number',
      'do-not-sell my personal information',
      'public data guidelines',
      'unsubscribe and delete my information',
      'data retention summary',
      'personal data notice',
      'do not sell',
      'how fastmail provide a secure service',
      'what data rakuten collects and why',
      'protection personal information',
      'data collection guidelines',
      'ccpa',
      'right to use',
      'ca residents notice',
      'security practices',
      'security notice',
      'security advisory',
      'personal data',
      'log keeping policy',
      'security of information',
      'personally identifiable information collected',
      'information use and disclosure',
      'data retention',
      'security and policy',
      'california opt out sale of data',
      'what information does standard notes collect about me?',
      'personalization and data help page',
      'safety and policy',
      'security intent',
      'site security',
      'prviacy policy',
      'personal information collection statement',
      'security agreement',
      'security information',
      'data collection',
      'data and information collection',
      'data handling',
      'data storage',
      'retention',
      'security and compliance',
      'personal information',
      'confidentiality',
      'data subjects',
      'encryption',
      'right of withdrawal',
      'collect',
      'protect',
      'share your information'
    ],
    'Vulnerability Disclosure Policy': [
      'vulnerability disclosure',
      'vulnerability',
      'responsible disclosure',
      'disclosure',
      'bugbounty'
    ],
    'Trackers Policy': [
      'cookies',
      'cookie',
      'coockie',
      'third party',
      'third-party',
      'third parties',
      'advertising',
      'interest-based',
      'internet-based',
      'tracking',
      'trackers',
      'tracker',
      'lokal lagring av data og informasjonskapsler',
      'политика за бисквитките',
      'ad choices',
      'do not track policy',
      'this service uses other services by google, who may track you.',
      'dnt',
      'ad policies'
    ],
    'Community Guidelines': [
      'influencer',
      'community guidelines',
      'etiquette policy',
      'code of conduct',
      'harassment',
      'hate speech',
      'правила сообщества «отзовик»',
      'kommentarregeln',
      'diretrizes de comunidade',
      'spam policy',
      'anti spam policy',
      'rules for community contests',
      'prohibited content',
      'content guidelines',
      'posting policy',
      'content policy',
      'coinbase markets trading rules',
      'community policy',
      'rules of conduct',
      'comments policy',
      'abusive behavior policy',
      'parody accounts',
      'submission',
      'content rules',
      'hacker news guidelines',
      'violent criminal organizations policy',
      'about diy tube video community',
      'anti-spam',
      'comment policy',
      'content protection',
      'user guidelines',
      'report abuse',
      'abuse warning',
      'complaint',
      'community rules',
      'community etiquette',
      'community usage',
      'information for authors'
    ],
    'Review Guidelines': [
      'notice and take down procedure',
      'content moderation guidelines',
      'repeat infringers policy',
      'infringement report policy',
      'takedown policy',
      'takedown',
      'take down',
      'review guidelines'
    ],
    'Law Enforcement Guidelines': [
      'law enforcement',
      'subpoena and warrant policy',
      'arbitration agreement',
      'grand jury subpoena for signal user data, eastern district of virginia',
      'dispute resolution policy',
      'subpoena',
      'arbitration'
    ],
    'Acceptable Use Policy': [
      'acceptable use',
      'acceptable',
      'fair usage',
      'fair use',
      'bandwidth policy'
    ],
    'Developer Terms': ['api', 'developer'],
    'Copyright Claims Policy': [
      'DMCA',
      'dmca',
      'dcma',
      'copyright',
      'intellectual property',
      'ip policy',
      'política de propriedade intelectual',
      '版权协议',
      'информация для правообладателей',
      'trademark',
      'reproduction of online materials policy'
    ],
    'Closed Captioning Policy': ['closed captioning policy'],
    'Legal Information': [
      'legal information',
      'legal info',
      'legal notices',
      'rechtliche hinweise',
      'legal',
      'liability disclaimer',
      'mentions légales',
      'haftungsausschluss',
      'general disclaimer',
      'regulamin',
      'you agree to defend, indemnify, and hold the service harmless in case of a claim related to your use of the service',
      'nondisclosure agreement',
      'indemnity',
      'domain name proxy agreement',
      'notices and disclaimers',
      'disclaimer',
      'site policies',
      'compliance',
      'export',
      'commercial entity',
      'transfer agreement',
      'paypal shops policy',
      'cctld',
      'support policy',
      'policy updates',
      'site notice',
      'academic policy',
      'fair credit reporting act rights',
      'gtld',
      'inventory policies',
      'responsible wagering statement',
      'notice'
    ],
    'Policy': [
      'policy',
      'policies'
    ],
    'Spam': [
      'super kamagra oral jelly',
      'убличная оферта',
      'halloween pumpkin bomber jacket',
      'avaforce 100 mg',
      'malegra 100 mg',
      'test',
      'mg',
      'json',
      'escort',
      'healthexcite',
      'icons/',
      'optimum-wellness',
      'jendralpoker',
      'can i buy postage with bitcoin?'
    ],
    'Frequently Asked Questions': [
      'faq',
      'What services does Standard Notes use for daily operation?',
      'Administrivia / TV Tropes Customs',
      'Pawelmar',
      'Credit Card Exclusions and Limitations',
      'f.a.q'
    ],
    'Merged': [
      'merged'
    ],
    # ask ota about other not being in the types
    'Other': [
      'charter',
      'chartre',
      'chatre',
      'charte',
      'impressum',
      'imprint',
      'binder2016/',
      'index.php',
      'samuel man barfield iii',
      '"10711 starit ln., dallas, texas 75229"',
      'tobi1.dk',
      'troy',
      'company blog',
      'here wi-fi opt-out',
      '"planio, redmine, and open source"',
      'automotive navigation from here',
      '"here wego, here application and here maps"',
      'example',
      'project goals',
      '"administrivia / the fic may be yours, but the trope page is ours"',
      'indexer',
      'newsmixer',
      'content ratings',
      'student registration document',
      'licence',
      'artist: avoid posting',
      'the fine print',
      'cc',
      'e.g해안선',
      'page footer',
      'main page',
      'pawelmar',
      'data-indexatie'
    ],
    'About': [
      'about'
    ],
    'Miscellaneous Agreement': [
      'agreement'
    ]
  }
end

# const types_map = {
#   'Acceptable Use Policy for Xfinity Internet': 'Acceptable Use Policy',
#   'Agreement': 'Terms of Service',
#   'Amazon Privacy Notice': 'Privacy Policy',
#   'API Terms of Use': 'Developer Terms',
#   'APIs Terms of Use': 'Developer Terms',
#   'Acceptable Use Policy': 'Terms of Service',
#   'All Policies': 'Terms of Service',
#   'Application-Based Services Terms of Use': 'Terms of Service',
#   'Cable Internet Terms of Use': 'Terms of Service',
#   'Canary Privacy Policy': 'Privacy Policy',
#   'Cbs Interactive Privacy Policy': 'Privacy Policy',
#   'Closed Captioning Policy': 'Closed Captioning Policy',
#   'Conditions of Use': 'Terms of Service',
#   'Consumer Terms of Sale': 'Terms of Service',
#   'Cookie Policy': 'Cookies Policy',
#   'Cookies and Privacy Policy - About Privacy': 'Privacy Policy',
#   'Copyright and Your use of the British Library Website': 'Terms of Service',
#   'Customer Privacy Policy': 'Privacy Policy',
#   DMCA: 'Copyright Policy',
#   'Data Policy': 'Privacy Policy',
#   'Data Use Policy': 'Privacy Policy',
#   EULA: 'Terms of Service',
#   'Software License Agreement': 'Terms of Service',
#   'Etiquette Policy': 'Community Guidelines',
#   'Flickr Privacy Policy': 'Privacy Policy',
#   'GOOGLE PRIVACY POLICY': 'Privacy Policy',
#   'Gizmo Privacy Policy': 'Privacy Policy',
#   'Host Guarantee Terms and Conditions': 'Seller Warranty',
#   'Intellectual Property': 'Copyright Claims Policy',
#   'Intellectual Property Policy': 'Copyright Claims Policy',
#   'Internet Terms of Service': 'Terms of Service',
#   # no current mapping for legal information
#   'Legal Info': 'Legal Information',
#   'Legal Information (Intuit)': 'Legal Information',
#   'Legal Notices': 'Legal Information',
#   'LinkedIn in Microsoft Applications with Your Personal Account': 'Single Sign-On Policy',
#   'Microsoft Services Agreement': 'Terms of Service',
#   'Microsoft Terms of Use': 'Terms of Service',
#   'Oath Privacy Center': 'Privacy Policy',
#   'PRIVACY POLICY': 'Privacy Policy',
#   Privacy: 'Privacy Policy',
#   'Privacy Notice': 'Privacy Policy',
#   'Privacy Statement': 'Privacy Policy',
#   'Privacy Policy Agreement': 'Privacy Policy',
#   'Privacy Policy and Terms of Use': 'Terms of Service',
#   'Privacy and Cookies Policy': 'Privacy Policy',
#   'Privacy for eero Devices': 'Privacy Policy',
#   'Rules on Resolving Image Piracy Complaints': 'Copyright Claims Policy',
#   'SAMSUNG PRIVACY POLICY FOR THE U.S.': 'Privacy Policy',
#   Security: 'Vulnerability Disclosure Policy',
#   'Security & Privacy': 'Privacy Policy',
#   'Security Advisory': 'Vulnerability Disclosure Policy',
#   'Signal Terms & Privacy Policy': 'Terms of Service',
#   'Term of Service': 'Terms of Service',
#   Terms: 'Terms of Service',
#   'Terms & Conditions': 'Terms of Service',
#   'Terms and Conditions': 'Terms of Service',
#   'Terms of Use': 'Terms of Service',
#   'Terms Of Use': 'Terms of Service',
#   'Terms and Conditions and Privacy Policy': 'Terms of Service',
#   'Terms and Conditions of Use': 'Terms of Service',
#   'Terms of Sale': 'Terms of Service',
#   'Terms of Service & Privacy Policy': 'Terms of Service',
#   'Terms of Service 1': 'Terms of Service',
#   'Terms of Service and License Agreement': 'Terms of Service',
#   'Terms of Service and Privacy': 'Terms of Service',
#   'Terms of Use (Consumer)': 'Terms of Service',
#   'Terms of Use - About Copyright': 'Terms of Service',
#   'Terms of Use and Privacy Policy': 'Terms of Service',
#   '"Third Party Advertising': ' Third Party Cookies',
#   'Universal Terms Of Service': 'Terms of Service',
#   'Use Agreement': 'Terms of Service',
#   'Visitor Agreement': 'Terms of Service',
#   'Vunerability Disclosure Program': 'Vulnerability Disclosure Policy',
#   'Web Notices and Terms of Use': 'Terms of Service',
#   'Website Terms of Service': 'Terms of Service',
#   'World Of Warcraft Terms Of Use Agreement': 'Terms of Service',
#   'YOUR PRIVACY & SECURITY': 'Privacy Policy',
#   'end-user-license-agreement': 'Terms of Service'
# }
